// Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, 
//generated by their encryption device "Enigma". To find the distribution of characters, he needs to find out
// how many times a particular character appears in a string. But, to feed the data into his computer,
// "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. 
//Since, he is busy making "Christopher" better, he asks you for help. 
//Help Alan find the frequency of characters in the encrypted strings in alphabetical order. 
//The string contains only lower case alphabets.


let n =4 ;
let string = "aman";
alanAndFreq(n, string);
function alanAndFreq(n, string) {
    let obj = {};
    string = string.split("").sort().join("");
    for(let i=0;i<n;i++) {
        if(obj[string[i]] === undefined) 
        {
            obj[string[i]] = 1;
        }
        else
        {
            obj[string[i]]++;
        }
    }
    for(let char in obj)
    {
        console.log(`${char}-${obj[char]}`);
    }
    
}